Repository Nilili-007/Nilili, pull requests merged in 2023-02, with the labels that each got.

#54 Header/Footer UI 구현
  public/login/google.png
  public/login/kakao.png
  public/login/naver.png
  src/App.tsx
  src/components/auth/Login.tsx
  src/components/auth/Register.tsx
  src/components/footer/Footer.tsx
  src/components/header/Header.tsx
Labels: UI

#56 Course UI 구현
  src/components/PostBtn.tsx
  src/components/PostHashTag.tsx
  src/components/PostTitle.tsx
  src/components/course/Comment.tsx
  src/components/course/CommentInput.tsx
  src/components/course/CourseHashTag.tsx
  src/components/course/CourseTitle.tsx
  src/components/course/DeleteModal.tsx
  src/components/course/LikeBtn.tsx
  src/pages/Course.tsx
  src/pages/Post.tsx
Labels: UI

#57 UI/post
  package.json
  src/components/course/Desc.tsx
  src/components/post/Modal.tsx
  src/components/post/Plan.tsx
  src/pages/Post.tsx
Labels: UI

#60 design: 드래그 앤 드롭 코스 변경 #45
  src/components/course/CourseDesc.tsx
  src/components/post/CourseLine.tsx
  src/components/post/Plan.tsx
  src/components/post/PostBtn.tsx
  src/components/post/PostHashTag.tsx
  src/components/post/PostSearchModal.tsx
  src/components/post/PostTitle.tsx
  src/pages/Course.tsx
  src/pages/Post.tsx
  tailwind.config.js
Labels: UI

#62 Header UI 수정 (weather 추가)
  src/components/header/Header.tsx
  src/components/header/Weather.tsx
Labels: enhancement

#68 로그인/회원가입 기능 구현
  public/login/facebook.png
  src/App.tsx
  src/components/auth/AuthForgot.tsx
  src/components/auth/Login.tsx
  src/components/auth/Modal.tsx
  src/components/auth/Register.tsx
  src/components/header/Header.tsx
  src/components/user/UserNameEdit.tsx
  src/shared/Router.tsx
Labels: enhancement

#69 UI/user
  src/App.tsx
  src/components/auth/AuthForgot.tsx
  src/components/auth/Modal.tsx
  src/components/course/index.ts
  src/components/index.ts
  src/components/main/index.ts
  src/components/post/index.ts
  src/components/search/index.ts
  src/components/user/UserCategoryBtn.tsx
  src/components/user/UserList.tsx
  src/components/user/index.ts
  src/pages/Course.tsx
  src/pages/Main.tsx
  src/pages/Post.tsx
  src/pages/Search.tsx
  src/pages/User.tsx
  src/shared/Router.tsx
Labels: UI

#70 로그인/회원가입 기능 수정 및 추가
  src/components/auth/AuthForgot.tsx
  src/components/auth/Modal.tsx
  src/components/header/Header.tsx
  src/shared/Router.tsx
Labels: enhancement

#72 feat : comment CRUD
  src/components/course/Comment.tsx
  src/components/course/CommentDesc.tsx
  src/components/course/CommentInput.tsx
  src/components/course/CourseTitle.tsx
  src/components/course/DeleteModal.tsx
  src/components/post/PostHashTag.tsx
  src/pages/Course.tsx
  src/redux/config/configStore.ts
  src/redux/modules/apiSlice.ts
  src/redux/modules/courseSlice.ts
  src/redux/modules/index.ts
Labels: enhancement

#73 로그인/회원가입 유효성 검사 수정
  src/components/auth/AuthForgot.tsx
  src/components/auth/Login.tsx
  src/components/auth/Modal.tsx
  src/components/auth/Register.tsx
  src/components/header/Header.tsx
Labels: enhancement

#74 Feat/post
  src/components/course/CourseDesc.tsx
  src/components/post/CourseLine.tsx
  src/components/post/PostCourseDesc.tsx
  src/components/post/PostCourseLine.tsx
  src/components/post/PostMap.tsx
  src/components/post/PostSearchModal.tsx
  src/components/post/PostTextarea.tsx
  src/components/post/index.ts
  src/pages/Post.tsx
  src/redux/config/configStore.ts
  src/redux/modules/temporarySlice.ts
Labels: enhancement

#84 로그인/회원가입 버그 수정 및 리팩토
  package-lock.json
  package.json
  src/components/auth/Login.tsx
  src/components/auth/Modal.tsx
  src/components/auth/Register.tsx
  src/components/auth/SocialLogin.tsx
Labels: bug

#85 Feat/get
  src/components/main/AfterLike.tsx
  src/components/main/BeforeRecent.tsx
  src/components/main/CityList.tsx
  src/components/main/HashtagList.tsx
  src/components/main/RandomList.tsx
  src/components/main/RecentList.tsx
  src/components/main/index.ts
  src/components/post/PostHashTag.tsx
  src/components/search/SearchList.tsx
  src/components/user/UserCategoryBtn.tsx
  src/components/user/UserList.tsx
  src/components/user/index.ts
  src/pages/Course.tsx
  src/pages/Main.tsx
  src/pages/NotFound.tsx
  src/pages/Post.tsx
  src/pages/Search.tsx
  src/pages/User.tsx
  src/pages/index.ts
  src/redux/modules/apiSlice.ts
  src/shared/Router.tsx
  src/types.d.ts
Labels: enhancement

#86 Feat/likes
  src/components/course/CommentAsc.tsx
  src/components/course/CommentDesc.tsx
  src/components/course/LikeBtn.tsx
  src/components/course/index.ts
  src/pages/Course.tsx
  src/pages/Post.tsx
  src/redux/modules/apiSlice.ts
Labels: enhancement

#87 Feat/post map
  src/components/post/PostBtn.tsx
  src/components/post/PostCourseInfo.tsx
  src/components/post/PostMap.tsx
  src/components/post/PostMarkers.tsx
  src/components/post/PostSearchModal.tsx
  src/components/post/PostTextarea.tsx
  src/components/post/PostTravelStatus.tsx
  src/pages/Post.tsx
  src/redux/modules/temporarySlice.ts
Labels: enhancement

#88 프로필 이미지 용량 제한 삭제
  src/components/user/ProfileEdit.tsx
Labels: bug

#89 feat : fix likes feature #30
  src/components/course/LikeBtn.tsx
  src/pages/Course.tsx
Labels: enhancement

#90 Fix/post memo
  src/components/post/PostCourseInfo.tsx
  src/components/post/PostMap.tsx
  src/components/post/PostMarkers.tsx
  src/components/post/PostSearchModal.tsx
  src/components/post/PostTextarea.tsx
  src/components/post/PostTitle.tsx
  src/components/post/PostTravelStatus.tsx
  src/pages/Post.tsx
Labels: enhancement

#91 Feat/delete course
  src/components/course/CourseTitle.tsx
  src/components/course/LikeBtn.tsx
  src/pages/Course.tsx
  src/redux/modules/apiSlice.ts
Labels: enhancement

#92 Feat/post header
  src/components/post/PostBtn.tsx
  src/components/post/PostCourseInfo.tsx
  src/components/post/PostHeader.tsx
  src/components/post/PostMap.tsx
  src/components/post/PostTextarea.tsx
  src/pages/Post.tsx
Labels: enhancement

#93 feat: 게시글 등록 #28
  src/pages/Post.tsx
Labels: enhancement

#94 Feat/post create coverimg
  src/components/post/PostBtn.tsx
  src/components/post/PostHeader.tsx
  src/components/post/PostMap.tsx
  src/components/post/PostTravelStatus.tsx
  src/components/post/index.ts
  src/pages/Post.tsx
  src/redux/config/configStore.ts
Labels: enhancement

#95 Feat/update course
  src/components/course/CommentDesc.tsx
  src/components/course/CourseHashTag.tsx
  src/components/course/CourseTitle.tsx
  src/components/course/EditCourse.tsx
  src/components/course/LikeBtn.tsx
  src/components/post/PostHashTag.tsx
  src/components/post/PostTitle.tsx
  src/pages/Course.tsx
  src/pages/Post.tsx
  src/redux/modules/apiSlice.ts
  src/types.d.ts
Labels: enhancement

#98 Feat/course read
  src/components/course/CourseHashTag.tsx
  src/components/course/CourseHeader.tsx
  src/components/course/CourseInfo.tsx
  src/components/course/CourseMap.tsx
  src/components/course/CourseMapMarker.tsx
  src/components/course/CourseTitle.tsx
  src/components/course/EditCourse.tsx
  src/components/course/index.ts
  src/components/main/AfterLike.tsx
  src/components/main/BeforeRecent.tsx
  src/components/post/PostCourseInfo.tsx
  src/components/post/PostHeader.tsx
  src/components/post/PostMarkers.tsx
  src/components/search/SearchList.tsx
  src/components/user/UserList.tsx
  src/pages/Course.tsx
  src/pages/Post.tsx
  src/types.d.ts
Labels: enhancement

#97 Feat/search
  src/components/header/Header.tsx
  src/components/main/AfterLike.tsx
  src/components/main/HashtagList.tsx
  src/components/post/PostHashTag.tsx
  src/components/search/SearchBox.tsx
  src/components/search/SearchList.tsx
  src/pages/Course.tsx
  src/pages/Search.tsx
  src/redux/config/configStore.ts
  src/redux/modules/apiSlice.ts
  src/redux/modules/searchSlice.ts
  src/types.d.ts
Labels: enhancement

#99 유저 프로필 / 프로필 모달 UI
  src/components/user/ProfileEdit.tsx
  src/components/user/UserName.tsx
  src/components/user/index.ts
  src/pages/User.tsx
Labels: UI

#100 feat : update Course Map #26
  src/components/course/EditCourse.tsx
  src/components/course/EditCourseMap.tsx
  src/components/course/EditCourseTitle.tsx
  src/components/post/PostMarkers.tsx
  src/redux/modules/apiSlice.ts
  src/types.d.ts
Labels: enhancement

#101 UI/course
  src/components/course/CourseHeader.tsx
  src/components/course/CourseManageButton.tsx
  src/components/course/CourseTitle.tsx
  src/components/course/index.ts
  src/pages/Course.tsx
Labels: UI

#103 fix:change editComponent to editPage #26
  src/components/course/CourseManageButton.tsx
  src/components/course/EditCourseMap.tsx
  src/components/course/index.ts
  src/components/edit/EditCourseTitle.tsx
  src/components/edit/index.ts
  src/pages/Course.tsx
  src/pages/EditCourse.tsx
  src/pages/index.ts
  src/redux/modules/apiSlice.ts
  src/shared/Router.tsx
Labels: enhancement

#104 Auth alert 추가 및 authforgot form 리팩토링
  src/components/auth/AuthForgot.tsx
  src/components/auth/Login.tsx
  src/components/auth/Register.tsx
  src/components/auth/SocialLogin.tsx
  src/components/header/Header.tsx
Labels: enhancement

#105 Fix : add validation on update course featre
  src/components/course/Comment.tsx
  src/components/edit/EditCourseTitle.tsx
  src/components/post/PostTitle.tsx
  src/pages/EditCourse.tsx
  src/pages/Post.tsx
  src/redux/modules/apiSlice.ts
Labels: enhancement

#108 design: edit Course page UI
  src/components/course/Comment.tsx
  src/components/course/CommentDesc.tsx
  src/components/course/CommentInput.tsx
  src/components/course/CourseHashTag.tsx
  src/components/course/CourseManageButton.tsx
  src/components/course/LikeBtn.tsx
  src/components/course/Pagenation.tsx
  src/pages/Course.tsx
Labels: UI

#110 design : editCoursePage UI
  src/components/course/CourseHashTag.tsx
  src/components/edit/EditCourseTitle.tsx
  src/components/post/PostHeader.tsx
  src/pages/EditCourse.tsx
Labels: UI

#111 검색 페이지 Pagenation 추가
  src/components/search/Pagenation.tsx
  src/components/search/SearchList.tsx
Labels: enhancement

#112 Fix/editcourse
  src/components/course/CourseHeader.tsx
  src/components/edit/EditCourseCategories.tsx
  src/components/edit/EditCourseInfo.tsx
  src/components/edit/EditCourseMap.tsx
  src/components/edit/index.ts
  src/components/post/PostCategories.tsx
  src/components/post/PostCourseInfo.tsx
  src/components/post/PostMap.tsx
  src/components/post/PostSearchModal.tsx
  src/components/post/PostTravelStatus.tsx
  src/components/post/index.ts
  src/components/search/SearchBox.tsx
  src/pages/EditCourse.tsx
  src/pages/Post.tsx
  src/redux/modules/apiSlice.ts
  src/types.d.ts
Labels: bug, UI

#113 feat : add personal profile image on Coursepage
  src/components/course/Comment.tsx
  src/components/course/CommentInput.tsx
  src/pages/Course.tsx
  src/pages/EditCourse.tsx
  src/pages/Post.tsx
  src/redux/modules/apiSlice.ts
  src/types.d.ts
Labels: enhancement

#115 design : change alert design on course page
  src/components/course/Comment.tsx
  src/components/course/CommentInput.tsx
  src/components/course/CourseManageButton.tsx
  src/pages/EditCourse.tsx
  src/pages/Post.tsx
Labels: bug, UI

#116 Feat/userpage
  src/App.tsx
  src/components/course/EditCourse.tsx
  src/components/course/LikeBtn.tsx
  src/components/edit/EditCourseCategories.tsx
  src/components/main/AfterLike.tsx
  src/components/main/BeforeRecent.tsx
  src/components/main/index.ts
  src/components/post/PostCategories.tsx
  src/components/post/PostHashTag.tsx
  src/components/search/SearchBox.tsx
  src/components/search/SearchList.tsx
  src/components/shared/ListMap.tsx
  src/components/shared/ListMapMarker.tsx
  src/components/shared/TopButton.tsx
  src/components/shared/index.ts
  src/components/user/UserCategoryBtn.tsx
  src/components/user/UserList.tsx
  src/pages/EditCourse.tsx
  src/pages/Post.tsx
  src/redux/modules/apiSlice.ts
Labels: enhancement

#145 Fix/fix created time, scroll position
  src/components/course/Comment.tsx
  src/components/main/AfterLike.tsx
  src/components/main/BeforeRecent.tsx
  src/components/post/PostCategories.tsx
  src/components/post/PostHeader.tsx
  src/components/search/SearchList.tsx
  src/components/user/UserList.tsx
  src/pages/Course.tsx
  src/pages/EditCourse.tsx
  src/redux/modules/apiSlice.ts
Labels: bug, enhancement

#146 UI/loading spinner
  package-lock.json
  package.json
  src/components/course/CommentDesc.tsx
  src/components/course/LikeBtn.tsx
  src/components/main/AfterLike.tsx
  src/components/main/BeforeRecent.tsx
  src/components/search/SearchBox.tsx
  src/components/search/SearchList.tsx
  src/components/user/UserList.tsx
  src/pages/Course.tsx
Labels: bug, UI

#147 SNS 공유 기능 추가
  package-lock.json
  package.json
  src/components/course/Share.tsx
  src/components/course/index.ts
  src/hooks/useScript.ts
  src/pages/Course.tsx
Labels: enhancement

#148 UI/hover
  src/components/course/CourseInfo.tsx
  src/components/course/CourseMapMarker.tsx
  src/components/main/AfterLike.tsx
  src/components/main/BeforeRecent.tsx
  src/components/search/SearchList.tsx
  src/components/shared/ListMap.tsx
  src/components/shared/ListMapMarker.tsx
  src/components/user/UserList.tsx
  src/types.d.ts
Labels: enhancement, UI

#149 SNS 공유 기능 UI 수정
  src/components/course/CommentDesc.tsx
  src/components/course/LikeBtn.tsx
  src/components/course/Share.tsx
  src/pages/Course.tsx
Labels: UI

#150 Fix/post
  package-lock.json
  package.json
  src/components/course/CourseInfo.tsx
  src/components/course/CourseManageButton.tsx
  src/components/edit/EditCourseInfo.tsx
  src/components/edit/EditCourseMap.tsx
  src/components/edit/EditCourseTextarea.tsx
  src/components/header/Header.tsx
  src/components/post/PostCourseInfo.tsx
  src/components/post/PostHeader.tsx
  src/components/post/PostMap.tsx
  src/components/post/PostMarkers.tsx
  src/components/post/PostSearchModal.tsx
  src/components/post/PostTextarea.tsx
  src/hooks/dummy.txt
  src/hooks/usePreventLeave.tsx
  src/pages/EditCourse.tsx
  src/pages/Post.tsx
  src/redux/modules/temporarySlice.ts
Labels: enhancement, UI
