Repository Nilili-007/Nilili, pull requests merged in 2023-03, with the labels that each got.

#151 UI/skeleton
  package-lock.json
  package.json
  public/assets/smallpath.png
  public/index.html
  src/App.tsx
  src/components/main/AfterLike.tsx
  src/components/main/BeforeRecent.tsx
  src/components/main/HashtagList.tsx
  src/components/main/Path.tsx
  src/components/main/ProgressiveImg.tsx
  src/components/search/SearchBox.tsx
  src/components/search/SearchList.tsx
  src/components/user/UserList.tsx
  src/index.css
  tailwind.config.js
Labels: UI

#152 탑 버튼 기능 변경
  src/components/shared/TopButton.tsx
Labels: enhancement

#153 feat : set amplitude
  package-lock.json
  package.json
  src/App.tsx
  src/components/auth/Login.tsx
  src/components/auth/Register.tsx
  src/components/auth/SocialLogin.tsx
  src/components/course/CommentInput.tsx
  src/components/course/LikeBtn.tsx
  src/components/course/Share.tsx
  src/components/edit/EditCourseCategories.tsx
  src/components/header/Header.tsx
  src/components/main/AfterLike.tsx
  src/components/main/BeforeRecent.tsx
  src/components/main/HashtagList.tsx
  src/components/main/Landing.tsx
  src/components/main/Path.tsx
  src/components/post/PostCategories.tsx
  src/components/post/PostHashTag.tsx
  src/components/search/SearchBox.tsx
  src/components/search/SearchList.tsx
  src/components/user/UserList.tsx
  src/pages/Course.tsx
  src/pages/EditCourse.tsx
  src/pages/Main.tsx
  src/pages/Post.tsx
  src/pages/Search.tsx
  src/pages/User.tsx
  src/utils/amplitude.ts
Labels: enhancement

#154 검색창 UI 수정
  src/components/edit/EditCourseCategories.tsx
  src/components/post/PostCategories.tsx
  src/components/post/PostHashTag.tsx
  src/components/search/SearchBox.tsx
  src/components/shared/ColorStyles.tsx
Labels: UI

#155 refactor : refactor pagenation and add responsive design
  package-lock.json
  package.json
  src/components/course/Comment.tsx
  src/components/course/CommentDesc.tsx
  src/components/course/CommentInput.tsx
  src/components/course/CourseHashTag.tsx
  src/components/course/CourseHeader.tsx
  src/components/course/CourseManageButton.tsx
  src/components/course/CourseMap.tsx
  src/components/course/LikeBtn.tsx
  src/components/course/Pagenation.tsx
  src/components/course/Share.tsx
  src/components/search/SearchList.tsx
  src/components/user/UserList.tsx
  src/hooks/usePagenation.ts
  src/index.tsx
  src/pages/Course.tsx
Labels: bug, enhancement, UI

#156 favicon, meta tag 설정
  public/favicon.ico
  public/favicon.png
  public/index.html
Labels: enhancement

#157 Feat/search
  src/components/course/CourseHashTag.tsx
  src/components/header/Header.tsx
  src/components/main/HashtagList.tsx
  src/components/post/PostHashTag.tsx
  src/components/search/SearchBox.tsx
  src/redux/config/configStore.ts
  src/redux/modules/apiSlice.ts
  src/redux/modules/searchSlice.ts
Labels: enhancement

#160 UI/edit course
  src/components/course/CourseMap.tsx
  src/components/edit/EditCourseCategories.tsx
  src/components/edit/EditCourseInfo.tsx
  src/components/edit/EditCourseMap.tsx
  src/components/edit/EditCourseMarkers.tsx
  src/components/edit/EditCourseTextarea.tsx
  src/components/post/PostCourse.tsx
  src/components/post/PostHeader.tsx
  src/components/post/PostMap.tsx
  src/components/post/PostSearchModal.tsx
  src/components/post/PostTextarea.tsx
  src/hooks/index.ts
  src/hooks/kakaoPagenation.ts
  src/hooks/usePreventLeave.ts
  src/hooks/usePreventLeave.tsx
  src/pages/EditCourse.tsx
  src/pages/Post.tsx
  src/redux/modules/courseSlice.ts
Labels: bug, UI

#159 Feat/meta tag
  package-lock.json
  package.json
  public/index.html
  public/ogImg.png
  src/App.tsx
  src/index.tsx
  src/utils/MetaTag.tsx
Labels: enhancement

#161 UI/post responsive
  src/components/course/Comment.tsx
  src/components/post/PostCategories.tsx
  src/components/post/PostHashTag.tsx
  src/components/post/PostHeader.tsx
  src/components/post/PostTravelStatus.tsx
  src/components/shared/ColorStyles.tsx
  src/pages/Post.tsx
  tailwind.config.js
Labels: bug, UI

#162 ui: 상세페이지 디자인 반영
  src/components/course/CourseInfo.tsx
  src/components/course/CourseMap.tsx
  src/components/course/CourseMapMarker.tsx
  src/components/edit/EditCourseMarkers.tsx
Labels: UI

#163 UI/user,main
  src/components/main/AfterLike.tsx
  src/components/main/BeforeRecent.tsx
  src/components/main/HashtagList.tsx
  src/components/main/Path.tsx
  src/components/user/UserCategoryBtn.tsx
  src/components/user/UserList.tsx
Labels: UI

#166 로그인/회원가입 페이지 (리팩토링)
  src/components/auth/AuthForgot.tsx
  src/components/auth/AuthForgotForm.tsx
  src/components/auth/Login.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/Modal.tsx
  src/components/auth/Register.tsx
  src/components/auth/RegisterForm.tsx
  src/components/auth/SocialLogin.tsx
  src/components/auth/index.ts
  src/components/header/Header.tsx
  src/pages/AuthForgot.tsx
  src/pages/Login.tsx
  src/pages/Register.tsx
  src/pages/index.ts
  src/shared/Router.tsx
Labels: bug, enhancement

#167 UI/edit responsive
  src/components/course/Comment.tsx
  src/components/course/CommentInput.tsx
  src/components/course/CourseHashTag.tsx
  src/components/course/CourseManageButton.tsx
  src/components/course/EditCourse.tsx
  src/components/edit/EditCourseCategories.tsx
  src/components/post/PostCategories.tsx
  src/components/post/PostHeader.tsx
  src/hooks/index.ts
  src/hooks/useBefore.ts
  src/hooks/useCommentPost.ts
  src/hooks/useDelete.ts
  src/hooks/useOption.ts
  src/pages/EditCourse.tsx
  src/pages/Post.tsx
  src/utils/firebase.ts
Labels: enhancement, UI

#168 Fix/share
  src/components/course/Share.tsx
Labels: bug

#169 Fix/use pagenation
  src/components/course/CommentDesc.tsx
  src/components/course/Pagenation.tsx
  src/components/edit/EditCourseCategories.tsx
  src/components/post/PostCategories.tsx
  src/components/post/PostHashTag.tsx
  src/components/post/PostHeader.tsx
  src/components/search/SearchBox.tsx
  src/components/search/SearchList.tsx
  src/components/search/SearchPagenation.tsx
  src/components/shared/Pagenation.tsx
  src/components/shared/index.ts
  src/components/user/UserList.tsx
  src/hooks/usePagenation.ts
  src/pages/EditCourse.tsx
  src/pages/Post.tsx
Labels: bug, UI

#171 Fix/auth
  src/components/auth/RegisterForm.tsx
  src/components/user/ProfileEdit.tsx
  src/components/user/UserInfoEdit.tsx
  src/components/user/UserName.tsx
Labels: enhancement

#173 Fix/course info
  src/components/common/CourseDeleteBtn.tsx
  src/components/common/CourseMemo.tsx
  src/components/common/CourseOrderBtns.tsx
  src/components/common/CoursePlaceInfo.tsx
  src/components/common/MapMarkers.tsx
  src/components/common/MobileCourseMemo.tsx
  src/components/common/MobileCourseToggleBtn.tsx
  src/components/common/SearchModal.tsx
  src/components/common/index.ts
  src/components/course/CourseInfo.tsx
  src/components/course/CourseManageButton.tsx
  src/components/course/CourseMap.tsx
  src/components/course/CourseMapMarker.tsx
  src/components/course/CourseMobile.tsx
  src/components/edit/EditCourseInfo.tsx
  src/components/edit/EditCourseMap.tsx
  src/components/edit/EditCourseMarkers.tsx
  src/components/edit/EditCourseMobile.tsx
  src/components/edit/EditCourseMobileMemo.tsx
  src/components/edit/EditCourseTextarea.tsx
  src/components/edit/index.ts
  src/components/header/Header.tsx
  src/components/post/PostCourse.tsx
  src/components/post/PostCourseDesc.tsx
  src/components/post/PostMap.tsx
  src/components/post/PostMobileCourse.tsx
  src/components/post/PostMobileMemo.tsx
  src/components/post/PostTextarea.tsx
  src/components/post/index.ts
  src/hooks/index.ts
  src/hooks/kakaoPagenation.ts
  src/hooks/useAddMemo.ts
  src/hooks/useDeleteCourse.ts
  src/hooks/useDownCourse.ts
  src/hooks/useFilterCourse.ts
  src/hooks/useHandleMemo.ts
  src/hooks/useKakaoMap.ts
  src/hooks/usePreventLeave.ts
  src/hooks/useUpCourse.ts
  src/pages/EditCourse.tsx
  src/redux/modules/courseSlice.ts
Labels: bug, enhancement

#174 fix : fix created time bugs
  src/components/course/Comment.tsx
  src/components/course/CommentDesc.tsx
  src/components/main/AfterLike.tsx
  src/components/main/BeforeRecent.tsx
  src/components/post/PostHeader.tsx
  src/components/search/SearchBox.tsx
  src/components/search/SearchList.tsx
  src/components/shared/ColorStyles.tsx
  src/components/shared/CreatedDate.tsx
  src/components/shared/Pagenation.tsx
  src/components/shared/index.ts
  src/components/user/UserList.tsx
  src/hooks/index.ts
  src/hooks/useDate.ts
  src/pages/Course.tsx
Labels: bug

#176 Fix/post
  src/components/common/CoursePlaceInfo.tsx
  src/components/common/PostInfo.tsx
  src/components/common/SearchModal.tsx
  src/components/common/SearchModalAddCourseBtn.tsx
  src/components/common/index.ts
  src/components/course/CourseHeader.tsx
  src/components/course/CourseManageButton.tsx
  src/components/course/CourseMobile.tsx
  src/components/edit/EditCourseCategories.tsx
  src/components/edit/EditCourseInfo.tsx
  src/components/edit/EditCourseMap.tsx
  src/components/edit/EditCourseMobile.tsx
  src/components/post/PostCategories.tsx
  src/components/post/PostCourse.tsx
  src/components/post/PostMap.tsx
  src/components/post/PostMobileCourse.tsx
  src/components/post/index.ts
  src/hooks/useDelete.ts
  src/pages/EditCourse.tsx
  src/pages/Post.tsx
Labels: bug, UI

#177 fix : add customer link and fix useDelete hook
  src/components/footer/Footer.tsx
  src/hooks/useDelete.ts
Labels: bug

#178 UI/list,banner
  package-lock.json
  package.json
  public/assets/path.png
  public/assets/smallpath.png
  src/components/header/Header.tsx
  src/components/header/Weather.tsx
  src/components/main/AfterLike.tsx
  src/components/main/BeforeRecent.tsx
  src/components/main/HashtagList.tsx
  src/components/main/Landing.tsx
  src/components/main/Path.tsx
  src/components/search/SearchBox.tsx
  src/components/search/SearchLanding.tsx
  src/components/search/SearchList.tsx
  src/components/shared/ListMap.tsx
  src/components/shared/TopButton.tsx
  src/components/user/UserCategoryBtn.tsx
  src/components/user/UserList.tsx
  src/components/user/UserName.tsx
  src/hooks/index.ts
  src/hooks/useGetScreenSize.ts
  src/index.css
  src/redux/modules/apiSlice.ts
  src/utils/firebase.ts
Labels: enhancement

#179 refactor: 글쓰기 & 수정페이지 - 등록/수정 및 취소 버튼 컴포넌트 재사용 #126
  src/components/common/MobileCourseMemo.tsx
  src/components/common/PostInfo.tsx
  src/components/common/PostManageBtns.tsx
  src/components/common/index.ts
  src/components/edit/EditCourseMobile.tsx
  src/components/post/PostMobileCourse.tsx
  src/hooks/index.ts
  src/hooks/useCancelPost.ts
  src/pages/EditCourse.tsx
  src/pages/Post.tsx
  src/redux/modules/courseSlice.ts
Labels: enhancement

#180 Fix/responsive
  src/components/header/Header.tsx
  src/components/main/AfterLike.tsx
  src/components/main/BeforeRecent.tsx
  src/components/main/HashtagList.tsx
  src/components/main/Landing.tsx
  src/components/search/SearchLanding.tsx
  src/index.css
Labels: bug, UI

#181 UI/mobile
  src/components/common/CourseMemo.tsx
  src/components/common/MapMarkers.tsx
  src/components/common/MobileCourseToggleBtn.tsx
  src/components/common/PostManageBtns.tsx
  src/components/common/SearchModal.tsx
  src/components/common/sweetalert.css
  src/components/course/CourseHeader.tsx
  src/components/course/CourseInfo.tsx
  src/components/course/CourseMapMarker.tsx
  src/components/course/CourseMobile.tsx
  src/components/edit/EditCourseCategories.tsx
  src/components/edit/EditCourseInfo.tsx
  src/components/edit/EditCourseMobile.tsx
  src/components/header/Header.tsx
  src/components/post/PostCourse.tsx
  src/components/post/PostMobileCourse.tsx
  src/hooks/useCancelPost.ts
  src/hooks/useDelete.ts
  src/hooks/useDeleteCourse.ts
  src/hooks/useFilterCourse.ts
  src/pages/EditCourse.tsx
  src/pages/Post.tsx
  src/redux/modules/courseSlice.ts
Labels: enhancement, UI

#182 fix : fix detail page bugs
  src/components/course/CourseHeader.tsx
  src/components/user/UserList.tsx
  src/hooks/useDate.ts
  src/redux/modules/apiSlice.ts
Labels: bug

#183 ui: 글쓰기 & 수정 & 상세페이지 수정
  src/components/common/MobileCourseToggleBtn.tsx
  src/components/common/PostInfo.tsx
  src/components/common/SearchModalAddCourseBtn.tsx
  src/components/course/CourseHeader.tsx
  src/components/course/CourseInfo.tsx
  src/components/edit/EditCourseMobile.tsx
  src/components/post/PostMobileCourse.tsx
  src/hooks/useDelete.ts
  src/pages/Post.tsx
Labels: UI

#184 Fix/course header
  src/components/common/SearchModalAddCourseBtn.tsx
  src/components/course/CommentInput.tsx
  src/components/course/CourseHeader.tsx
  src/components/post/PostCourse.tsx
  src/hooks/useDelete.ts
  src/pages/EditCourse.tsx
Labels: UI

#185 일부 UI 수정
  src/components/auth/RegisterForm.tsx
  src/components/course/Share.tsx
  src/components/header/Header.tsx
  src/components/user/ProfileEdit.tsx
  src/components/user/UserName.tsx
  src/pages/NotFound.tsx
Labels: UI

#187 fix : edit course header position #136 #139 #140
  src/components/common/PostInfo.tsx
  src/components/course/CourseHeader.tsx
Labels: UI

#189 Fix/search select
  src/components/edit/EditCourseCategories.tsx
  src/components/post/PostCategories.tsx
  src/components/post/PostHashTag.tsx
  src/components/search/SearchBox.tsx
  src/components/search/SearchList.tsx
  src/components/shared/MultiStyles.tsx
  src/components/shared/SingleStyles.tsx
  src/components/shared/index.ts
  src/pages/Post.tsx
Labels: UI

#190 Fix/feedback
  src/components/header/Header.tsx
  src/components/main/AfterLike.tsx
  src/components/main/AfterRecent.tsx
  src/components/main/BeforeRecent.tsx
  src/components/main/HashtagList.tsx
  src/components/main/Landing.tsx
  src/components/main/Path.tsx
  src/components/search/SearchBox.tsx
  src/components/search/SearchLanding.tsx
  src/components/search/SearchList.tsx
  src/components/user/UserCategoryBtn.tsx
  src/components/user/UserList.tsx
  src/components/user/UserName.tsx
  src/index.css
Labels: UI

#192 Fix/kakaomap
  package-lock.json
  package.json
  src/components/common/PostInfo.tsx
  src/components/common/SearchModal.tsx
  src/components/course/CourseHeader.tsx
  src/hooks/index.ts
  src/hooks/useDebounce.ts
  src/hooks/useKakaoMap.ts
  src/redux/modules/courseSlice.ts
Labels: enhancement

#193 Refactor/input
  package-lock.json
  package.json
  src/components/common/PostInfo.tsx
  src/components/course/CommentInput.tsx
  src/components/course/CourseHeader.tsx
  src/components/search/SearchBox.tsx
  src/hooks/index.ts
  src/hooks/useCommentPost.ts
  src/hooks/useInput.ts
  src/pages/EditCourse.tsx
  src/pages/Post.tsx
  src/types.d.ts
Labels: enhancement

#194 refactor: 글쓰기 & 수정페이지 - 메모 작성란 debounce 적용
  src/components/common/CourseMemo.tsx
  src/components/common/MapMarkers.tsx
  src/components/common/SearchModal.tsx
  src/components/course/CourseMapMarker.tsx
Labels: enhancement

#196 fix: 글쓰기 & 수정페이지 - 커버 이미지 업로드 예외 처리
  src/components/common/PostInfo.tsx
  src/components/common/index.ts
  src/components/post/index.ts
Labels: bug

#198 feat: 커버 이미지 옵션에 링크 추가
  src/components/common/PostInfo.tsx
Labels: enhancement

#199 refactor : add lazy-loading
  src/pages/index.ts
  src/shared/Router.tsx
Labels: enhancement

#200 feat: heic 이미지 업로드 및 이미지 리사이즈 기능 구현
  package-lock.json
  package.json
  src/components/common/PostInfo.tsx
Labels: enhancement

#202 fix: swal timer 일부 수정
  src/components/auth/RegisterForm.tsx
Labels: bug

#203 Feat/cover img
  src/components/common/PostInfo.tsx
Labels: enhancement

#204 fix: 커버 갤러리 이미지 일부 webp 확장자로 교체
  public/assets/covers/autumn2.avif
  public/assets/covers/autumn2.webp
  public/assets/covers/bukchon-hanok-village.avif
  public/assets/covers/bukchon-hanok-village.webp
  public/assets/covers/hanok.webp
  public/assets/covers/machang-bridge.webp
  public/assets/covers/persimmon.webp
  public/assets/covers/scenery.webp
  public/assets/covers/sunset.webp
  public/assets/covers/suwon.webp
  public/assets/covers/suwon2.webp
  public/assets/covers/top.webp
  src/components/common/index.ts
  src/hooks/usePreventLeave.ts
Labels: bug

#205 Fix/kakaomap search
  public/assets/covers/autumn-leave.webp
  public/assets/covers/autumn.webp
  public/assets/covers/bird.webp
  public/assets/covers/busan-night.webp
  public/assets/covers/castle.webp
  public/assets/covers/city1.webp
  public/assets/covers/daegu.webp
  public/assets/covers/daegu2.webp
  public/assets/covers/flower.webp
  public/assets/covers/forest-road.webp
  public/assets/covers/gamcheon-culture-village.webp
  public/assets/covers/haeundae.webp
  public/assets/covers/han-river.webp
  public/assets/covers/jeju-flower.webp
  public/assets/covers/jeju-greentea.webp
  public/assets/covers/jeju-sea-2.webp
  public/assets/covers/jeju-sea.webp
  public/assets/covers/jusang-joint.webp
  public/assets/covers/sea.webp
  public/assets/covers/seoul-1.webp
  public/assets/covers/seoul-olympic-park.webp
  public/assets/covers/snow.webp
  src/components/common/MapMarkers.tsx
  src/components/common/PostInfo.tsx
  src/components/common/SearchModal.tsx
  src/components/common/index.ts
  src/components/course/CourseMap.tsx
  src/components/course/CourseMapMarker.tsx
  src/components/edit/EditCourseMap.tsx
  src/components/post/PostMap.tsx
Labels: bug, UI

#206 Fix/cover img
  package-lock.json
  public/assets/covers/autumn-leave.avif
  public/assets/covers/autumn.avif
  public/assets/covers/bird.avif
  public/assets/covers/busan-night.avif
  public/assets/covers/castle.avif
  public/assets/covers/city1.avif
  public/assets/covers/daegu.avif
  public/assets/covers/daegu2.avif
  public/assets/covers/flower.avif
  public/assets/covers/forest-road.avif
  public/assets/covers/gamcheon-culture-village.avif
  public/assets/covers/haeundae.avif
  public/assets/covers/han-river.avif
  public/assets/covers/hanok.avif
  public/assets/covers/jeju-flower.avif
  public/assets/covers/jeju-greentea.avif
  public/assets/covers/jeju-sea-2.avif
  public/assets/covers/jeju-sea.avif
  public/assets/covers/jusang-joint.avif
  public/assets/covers/machang-bridge.avif
  public/assets/covers/persimmon.avif
  public/assets/covers/scenery.avif
  public/assets/covers/sea.avif
  public/assets/covers/seoul-1.avif
  public/assets/covers/seoul-olympic-park.avif
  public/assets/covers/snow.avif
  public/assets/covers/sunset.avif
  public/assets/covers/suwon.avif
  public/assets/covers/suwon2.avif
  src/components/common/MapMarkers.tsx
  src/components/common/PostInfo.tsx
  src/components/course/CourseMapMarker.tsx
  src/pages/Post.tsx
Labels: enhancement

#207 feat: 모달밖 클릭시 모달 닫기
  src/components/common/MapMarkers.tsx
  src/components/common/PostInfo.tsx
  src/components/common/SearchModal.tsx
  src/components/course/CourseHeader.tsx
  src/components/course/CourseMapMarker.tsx
  src/components/edit/EditCourseMap.tsx
  src/components/post/PostMap.tsx
  src/hooks/index.ts
  src/hooks/useCloseModal.ts
  src/pages/EditCourse.tsx
  src/pages/Post.tsx
Labels: enhancement

#209 fix: height 지정
  src/pages/Login.tsx
  src/pages/Register.tsx
Labels: UI

#208 Refactor/custom hook
  public/favicon.png
  src/components/common/PostInfo.tsx
  src/components/course/CourseHeader.tsx
  src/components/header/Header.tsx
  src/components/main/AfterLike.tsx
  src/components/main/AfterRecent.tsx
  src/components/main/BeforeRecent.tsx
  src/components/main/HashtagList.tsx
  src/components/main/Landing.tsx
  src/components/main/Path.tsx
  src/components/post/PostMap.tsx
  src/components/search/SearchBox.tsx
  src/components/search/SearchLanding.tsx
  src/components/search/SearchList.tsx
  src/components/shared/MultiStyles.tsx
  src/components/shared/SingleStyles.tsx
  src/components/user/UserCategoryBtn.tsx
  src/components/user/UserList.tsx
  src/components/user/UserName.tsx
  src/hooks/index.ts
  src/hooks/useBefore.ts
  src/hooks/useFilterData.ts
  src/index.css
  src/pages/Course.tsx
  src/pages/EditCourse.tsx
  src/pages/Post.tsx
  tailwind.config.js
Labels: enhancement, UI

#213 ui: 글쓰기 & 상세 & 수정페이지 UI 수정
  src/components/common/PostInfo.tsx
  src/components/common/SearchModal.tsx
  src/components/course/CourseHeader.tsx
  src/components/course/CourseInfo.tsx
  src/components/edit/EditCourseCategories.tsx
  src/components/edit/EditCourseInfo.tsx
  src/components/post/PostCourse.tsx
  src/pages/Post.tsx
Labels: UI
